
name: tests

on: [push]


jobs:
  black:
    name: Style Reformatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade Pip lmao
        run: pip install -U pip
      - name: Install requirements
        run: |
          pip install -U autoflake
          pip install -U black
          pip install -U isort
          pip install -U pre-commit
      - name: Style reformatting
        continue-on-error: true
        run: |
          python3.9 -m black ../../
          python3.9 -m isort ../../
          python3.9 -m autoflake --recursive --in-place --remove-all-unused-imports ../../
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "Style Reformatting"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
